#!/usr/bin/env bash
set -o nounset
set -o errexit

rm -rf testing-env
mkdir testing-env
cd testing-env
cat ../.jpmignore ../.jpmignore-testing-env > .jpmignore
ln -s ../Gruntfile.js .
ln -s ../node_modules .
ln -s ../data .
ln -s ../coverage/instrument/lib .
ln -s ../package.json .
ln -s ../test .
echo "OK" $0
